apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/adreasnow/k8s-play.git
              revision: HEAD
              directories:
                - path: "argocd-appsets/apps/*"
          - clusters:
              selector: {}
              values:
                clusterName: "{{ .name }}"
  template:
    metadata:
      name: "{{ .path.basename }}-{{ .values.clusterName }}"
    spec:
      project: apps
      source:
        repoURL: https://github.com/adreasnow/k8s-play.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
        helm:
          valueFiles:
            - values.yaml
            - "values-{{ .values.clusterName }}.yaml"
          ignoreMissingValueFiles: true
      destination:
        server: "{{ .server }}"
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true