apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kiali-operator
      version: 2.24.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      interval: 1h
  targetNamespace: kiali-operator
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cr:
      namespace: istio-system
      create: true
      spec:
        auth:
          strategy: anonymous
        external_services:
          istio:
            gateway_api_classes_label_selector: "app.kubernetes.io/name=traefik"
          prometheus:
            url: http://victoriametrics-victoriametrics-vm-server.victoriametrics.svc.cluster.local:8428
