# Disable the default IngressClass since we use Gateway API
ingressClass:
  enabled: false

# Providers tell Traefik where to find routing configuration
providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
    nativeLBByDefault: true # Use native load balancer for Gateway listeners to keep traffic local

# Gateway Listeners
gateway:
  listeners:
    web:
      port: 80
      protocol: HTTP
      namespacePolicy:
        from: All

    websecure:
      port: 443
      protocol: HTTPS
      namespacePolicy:
        from: All
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: traefik-tls-cert  # the Secret we created before the installation
          group: ""


# EntryPoints are the network listeners for incoming traffic
ports:
  websecure:
    port: 443
    nodePort: 30001
  web:
    port: 80
    nodePort: 30000
    http:
      redirections: # redirects non-tls traffic to the 'websecure' entry point
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
