apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: namespaces-base
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
spec:
  inputs:
    - name: traefik
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.name >>
        # labels:
        #   istio.io/dataplane-mode: ambient
        # annotations:
        #   networking.istio.io/traffic-distribution: PreferSameZone
