apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: namespaces-base
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
spec:
  wait: true
  inputs:
    - name: traefik
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.name >>
      spec:
        trafficDistribution: PreferClose
        # labels:
        #   istio.io/dataplane-mode: ambient
        # annotations:
        #   networking.istio.io/traffic-distribution: PreferSameZone
