apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: linkerd-certificates
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
    fluxcd.controlplane.io/reconcileTimeout: 10m
spec:
  wait: true
  inputs:
    - name: linkerd-trust-root-issuer
      path: ./fluxcd/infrastructure/common/resources/linkerd/certificates/1-trust-root-issuer

    - name: linkerd-trust-anchor
      path: ./fluxcd/infrastructure/common/resources/linkerd/certificates/2-trust-anchor
      deps: [linkerd-trust-root-issuer]

    - name: linkerd-identity-issuer
      path: ./fluxcd/infrastructure/common/resources/linkerd/certificates/3-identity-issuer
      deps: [linkerd-trust-anchor]

    - name: linkerd-identity-issuer-cert
      path: ./fluxcd/infrastructure/common/resources/linkerd/certificates/4-identity-issuer-cert
      deps: [linkerd-identity-issuer-cert]

    - name: linkerd-trust-bundle
      path: ./fluxcd/infrastructure/common/resources/linkerd/certificates/5-trust-bundle
      deps: [linkerd-trust-bundle]

  resourcesTemplate: |
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << inputs.name >>
      namespace: flux-system
    spec:
      interval: 10m
      timeout: 10m
      retryInterval: 1m
      path: << inputs.path >>
      prune: false
      force: false
      wait: true
      sourceRef:
        kind: GitRepository
        name: flux-system
    <<- if get inputs "deps" >>
      dependsOn:
      <<- range $dep := inputs.deps >>
        - name: << $dep >>
      <<- end >>
    <<- end >>
