apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: infrastructure-base
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
spec:
  inputs:
    - name: namespaces-base
      path: ./fluxcd/infrastructure/base/namespaces

    - name: cert-manager
      path: ./fluxcd/infrastructure/base/resources/cert-manager

    - name: cluster-issuer
      path: ./fluxcd/infrastructure/base/resources/cluster-issuer
      deps: [cert-manager]

    - name: kro
      path: ./fluxcd/infrastructure/base/resources/kro

    - name: kro-definitions
      path: ./fluxcd/infrastructure/base/resources/kro-definitions
      deps: [kro]
      useClusterVars: true

    - name: traefik
      path: ./fluxcd/infrastructure/base/resources/traefik
      deps: [cluster-issuer, namespaces-base]
      useClusterVars: true

  resourcesTemplate: |
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << inputs.name >>
      namespace: flux-system
    spec:
      interval: 10m
      timeout: 10m
      retryInterval: 1m
      path: << inputs.path >>
      prune: << get inputs "prune" | default "true" >>
      force: << get inputs "force" | default "false" >>
      wait: true
      sourceRef:
        kind: GitRepository
        name: flux-system
    <<- if get inputs "deps" >>
      dependsOn:
      <<- range $dep := inputs.deps >>
        - name: << $dep >>
      <<- end >>
    <<- end >>
    <<- if get inputs "useClusterVars" >>
      postBuild:
        substituteFrom:
          - kind: ConfigMap
            name: cluster-vars
    <<- end >>
