apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 10m
  path: ./fluxcd/apps/base/demo
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
