    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: istio-base
      namespace: flux-system
    spec:
      interval: 10m
      timeout: 10m
      retryInterval: 1m
      path: ./fluxcd/infrastructure/common/resources/istio/1-istio
      prune: false
      force: false
      wait: true
      sourceRef:
        kind: GitRepository
        name: flux-system
