apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resourcesets
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  path: ./flux-operator/resourcesets/production
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system