apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: infrastructure-common
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
    fluxcd.controlplane.io/reconcileTimeout: 10m
spec:
  wait: true
  inputs:

    - name: kro
      path: ./fluxcd/infrastructure/common/resources/kro

    - name: cert-manager
      path: ./fluxcd/infrastructure/common/resources/cert-manager

    - name: gateway-api
      path: ./fluxcd/infrastructure/common/resources/gateway-api

    - name: caretta
      path: ./fluxcd/infrastructure/common/resources/caretta

    - name: cluster-issuer
      path: ./fluxcd/infrastructure/common/resources/cluster-issuer
      prune: false
      deps: [cert-manager]

    - name: istio
      path: ./fluxcd/infrastructure/common/resources/istio
      deps: [cluster-issuer, gateway-api]

    - name: kiali
      path: ./fluxcd/infrastructure/common/resources/kiali
      deps: [istio]

    - name: kiali-service
      path: ./fluxcd/infrastructure/common/resources/kiali-service
      deps: [kiali]
      substituteFrom:
        - name: cluster-vars

    - name: namespaces
      path: ./fluxcd/infrastructure/common/resources/namespaces
      deps: [istio]
      substituteFrom:
        - name: cluster-vars

    - name: netowrking-extras
      path: ./fluxcd/infrastructure/common/resources/networking-extras
      deps: [istio]

    - name: kro-definitions
      path: ./fluxcd/infrastructure/common/resources/kro-definitions
      deps: [kro, istio]
      substituteFrom:
        - name: cluster-vars

    - name: flux-operator-dashboard
      path: ./fluxcd/infrastructure/common/resources/flux-operator-dashboard
      deps: [istio]
      substituteFrom:
        - name: cluster-vars

  resourcesTemplate: |
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << inputs.name >>
      namespace: flux-system
    spec:
      interval: 10m
      timeout: 10m
      retryInterval: 1m
      path: << inputs.path >>
      prune: << get inputs "prune" | default "true" >>
      force: << get inputs "force" | default "false" >>
      wait: true
      sourceRef:
        kind: GitRepository
        name: flux-system
    <<- if get inputs "deps" >>
      dependsOn:
      <<- range $dep := inputs.deps >>
        - name: << $dep >>
      <<- end >>
    <<- end >>
    <<- if get inputs "substituteFrom" >>
      postBuild:
        substituteFrom:
      <<- range $sub := inputs.substituteFrom >>
          - kind: << get $sub "kind" | default "ConfigMap" >>
            name: << $sub.name >>
      <<- end >>
    <<- end >>
