apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-ks.yaml
  - flux-operator-dashboard-ks.yaml
  - gateway-api-ks.yaml
  - istio-ks.yaml
  - kiali-ks.yaml
  - kro-definitions-ks.yaml
  - kro-ks.yaml
  - telemetry-ks.yaml
  - namespaces-ks.yaml
  - networking-extras-ks.yaml
  # - otel-ks.yaml
  - alloy-ks.yaml
  - traefik-ks.yaml
