apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/adreasnow/k8s-play.git
    targetRevision: HEAD
    path: argocd-apps/apps/demo
    helm:
      valueFiles:
        - values.yaml
        - values-CLUSTER.yaml
      ignoreMissingValueFiles: true
  destination:
    server: none
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
