apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - gateway-api.yaml
  - namespaces.yaml
  - cluster-issuer.yaml
  - kro.yaml
  - kro-definitions.yaml
  - traefik.yaml
  - demo.yaml