# https://fluxoperator.dev/docs/crd/fluxinstance/
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: 2.x
    registry: ghcr.io/fluxcd
    artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller # TODO: configure slack notifications
  cluster:
    type: aws
    size: medium
    multitenant: false # TODO?
    networkPolicy: true
    domain: cluster.local
  sync: # TODO: configure for github app
    kind: GitRepository
    url: ssh://git@github.com/adreasnow/k8s-play
    ref: refs/heads/main
    path: fluxcd/clusters/techteamtools-staging
    pullSecret: flux-system
    # provider: github
