apiVersion: bellroy.com/v1alpha1
kind: MeshedService
metadata:
  name: demo
  namespace: demo
spec:
  name: demo
  replicas: 2

  container:
    image: argoproj/rollouts-demo:purple
    ports:
      - port: 8080
        protocol: TCP

  ingress:
    hostname: demo
    enabled:
      internal: true
      external: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
