apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: alloy-values
    namespace: flux-system
    files:
      - values=values.yaml
  - name: alloy-config
    namespace: flux-system
    files:
      - config=config.hcl
