apiVersion: bellroy.com/v1alpha1
kind: MeshedService
metadata:
  name: mimir
  namespace: mimir
spec:
  service: mimir-mimir-gateway
  hostname: mimir.telemetry
  internal:
    http:
      enabled: true
      ports: [80]
  external:
    http:
      enabled: true
      ports: [80]
