apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: mimir-distributed
      version: 6.0.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  targetNamespace: telemetry
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: mimir-values
      valuesKey: values
  values:
    fullnameOverride: telemetry-mimir
    auth:
      multitenancy_enabled: true
    mimir:
      structuredConfig:
        no_auth_tenant: ${clusterName}

  # mimir:
  #   structuredConfig:
  #     common:
  #       storage:
  #         backend: s3
  #         s3:
  #           endpoint: s3.us-east-2.amazonaws.com
  #           region: us-east
  #           secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  #           access_key_id: "${AWS_ACCESS_KEY_ID}"
