apiVersion: bellroy.com/v1alpha1
kind: MeshedService
metadata:
  name: tempo
  namespace: tempo
spec:
  service: tempo-tempo
  hostname: tempo.telemetry
  internal:
    http:
      enabled: true
      ports: [3200, 4317]
  external:
    http:
      enabled: true
      ports: [3200]
