apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tempo
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
      interval: 1h
  targetNamespace: tempo
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicas: ${azCount}
    fullnameOverride: tempo-tempo
    multitenancyEnabled: true
    tempo.tag: 2.10.4

    # storage:
    #   trace:
    #     backend: s3
    #     s3:
    #       bucket: ${tempoBucketName}
    #       endpoint: s3.${awsRegion}.amazonaws.com

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: StatefulSet
              name: tempo-tempo
            patch: |
              - op: add
                path: /spec/template/spec/topologySpreadConstraints
                value:
                  - maxSkew: 1
                    topologyKey: topology.kubernetes.io/zone
                    whenUnsatisfiable: DoNotSchedule
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: tempo-tempo
          - target:
              version: v1
              kind: Service
              name: tempo-tempo
            patch: |
              - op: add
                path: /spec/trafficDistribution
                value: PreferClose
