ingester:
  replicas: ${azCount}

distributor:
  replicas: ${azCount}

querier:
  replicas: ${azCount}

query-frontend:
  replicas: ${azCount}

compactor: {}

gateway:
  replicas: ${azCount}
  service:
    # trafficDistribution: PreferClose
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
