apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkerd
  namespace: linkerd-viz
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    - linkerd.admin.${domain}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: web
          port: http
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  podSelector:
    matchLabels:
      component: web
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkerd-viz-mesh-route
  namespace: linkerd-viz
spec:
  parentRefs:
    - name: linkerd-viz
      kind: Server
      group: policy.linkerd.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: linkerd-viz-all-meshed-clients
  namespace: linkerd-viz
spec:
  identities:
    - "*"
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: linkerd-viz-allow-mesh
  namespace: linkerd-viz
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: linkerd-viz-mesh-route
  requiredAuthenticationRefs:
    - name: linkerd-viz-all-meshed-clients
      kind: MeshTLSAuthentication
      group: policy.linkerd.io
