apiVersion: kro.run/v1alpha1
kind: Service
metadata:
  name: demo-2
  namespace: demo
spec:
  name: demo-2
  replicas: 2
  image: argoproj/rollouts-demo:purple
  hostname: demo-2.docker.localhost
  ports:
    - port: 8080
      protocol: TCP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
