apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: app-namespaces
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 10m
spec:
  commonMetadata:
    annotations:
      fluxcd.controlplane.io/prune: enabled
  wait: true
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          template: ${namespaceRSIPTemplateName}
  resources:
    - apiVersion: kro.run/v1alpha1
      kind: MeshedNamespace
      metadata:
        name: << inputs.name >>
        namespace: flux-system
      spec:
        name: << inputs.name >>
