apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: app-namespaces
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
spec:
  commonMetadata:
    annotations:
      fluxcd.controlplane.io/prune: enabled
  wait: true
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          template: ${namespaceRSIPTemplateName}
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.name >>
        annotations:
          linkerd.io/inject: enabled
      spec:
        trafficDistribution: PreferClose

    # Allows pods in the same namespace to communicate with each other
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-same-namespace-communication
        namespace: << inputs.name >>
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: << inputs.name >>

      # Blocks egress to system namespaces
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: block-system-namespace-egress
        namespace: << inputs.name >>
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - to:
              - namespaceSelector:
                  matchExpressions:
                    - key: kubernetes.io/metadata.name
                      operator: NotIn
                      values:
                        - kube-system
                        - kube-public
                        - kube-node-lease

      # Allow DNS resolution for the namespace
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-dns-egress
        namespace: << inputs.name >>
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: kube-system
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
            ports:
              - port: 53
                protocol: UDP
              - port: 53
                protocol: TCP

      # Allow egress to external networks
      # Does not overwrite existing DENY rules
      # all east-west traffic still goes through Istio with STRICT routing
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-egress
        namespace: << inputs.name >>
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - {} # Empty rule = allow all egress
