apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-selfsigned-tls
  namespace: traefik-proxy
spec:
  secretName: local-selfsigned-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: "*.docker.localhost"
  dnsNames:
    - "*.docker.localhost"
    - "docker.localhost"
  duration: 8760h    # 1 year
  renewBefore: 360h  # renew 15 days before expiry
