apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: infrastructure-base
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
    fluxcd.controlplane.io/reconcileTimeout: 10m
spec:
  wait: true
  inputs:
    - name: istio-base
      path: ./fluxcd/infrastructure/base/resources/istio/1-istio-base

    # - name: istiod
    #   path: ./fluxcd/infrastructure/base/resources/istio/2-istiod
    #   deps: [istio-base]

    # - name: istio-cni
    #   path: ./fluxcd/infrastructure/base/resources/istio/3-istio-cni
    #   deps: [istiod]

    # - name: ztunnel
    #   path: ./fluxcd/infrastructure/base/resources/istio/4-ztunnel
    #   deps: [istio-cni]

    # - name: configuration
    #   path: ./fluxcd/infrastructure/base/resources/istio/5-configuration
    #   deps: [ztunnel]

  resourcesTemplate: |
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << inputs.name >>
      namespace: flux-system
    spec:
      interval: 10m
      timeout: 10m
      retryInterval: 1m
      path: << inputs.path >>
      prune: << get inputs "prune" | default "false" >>
      force: << get inputs "force" | default "false" >>
      wait: true
      sourceRef:
        kind: GitRepository
        name: flux-system
    <<- if get inputs "deps" >>
      dependsOn:
      <<- range $dep := inputs.deps >>
        - name: << $dep >>
      <<- end >>
    <<- end >>
