apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otel-daemonset
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  retryInterval: 1m
  path: ./fluxcd/infrastructure/common/resources/telemetry/otel/collectors/otel-daemonset
  prune: true
  force: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: otel-operator
    - name: telemetry-namespaces
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
