apiVersion: bellroy.com/v1alpha1
kind: MeshedService
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  service: kiali
  hostname: kiali.admin
  internal:
    http:
      enabled: true
      ports: [20001]
  external:
    http:
      enabled: true
      ports: [20001]
