apiVersion: v1
kind: Service
metadata:
  name: kiali
spec:
  trafficDistribution: PreferClose # Prefer same AZ/same node endpoints (k8s)
  selector:
    app: kiali
  ports:
    - port: 20001
      targetPort: 20001
      protocol: TCP
