apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/kubernetes-sigs/gateway-api/release-manifests
  ref:
    tag: v1.5.1
