apiVersion: bellroy.com/v1alpha1
kind: MeshedService
metadata:
  name: loki
spec:
  service: telemetry-loki-gateway
  hostname: loki.telemetry
  internal:
    http:
      enabled: true
      ports: [80]
  external:
    http:
      enabled: true
      ports: [80]
