loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

ruler.enabled: false

deploymentMode: Distributed

global:
  service:
    trafficDistribution: PreferClose

# This exposes the Loki gateway so it can be written to and queried externaly
gateway:
  replicas: ${azCount}
  service:
    type: LoadBalancer
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: loki-loki

ingester:
  replicas: ${azCount}
  zoneAwareReplication:
    enabled: false
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: loki-loki

querier:
  replicas: ${azCount} # Improve query performance via parallelism
  maxUnavailable: 1
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: loki-loki

queryFrontend:
  replicas: 2
  maxUnavailable: 1
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: loki-loki

queryScheduler:
  replicas: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: loki-loki
distributor:
  replicas: ${azCount}
  maxUnavailable: 1
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: loki-loki

compactor:
  replicas: 1

indexGateway:
  replicas: 2
  maxUnavailable: 1

# reasonable defaults
memcached: {}
memcachedExporter: {}
resultsCache: {}
chunksCache: {}

# disabled by default
bloomPlanner: {}
bloomBuilder: {}
patternIngester: {}
overridesExporter: {}
bloomGateway: {}
