apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  retryInterval: 1m
  path: ./fluxcd/apps/bellroy
  prune: false
  force: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
