apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - worker.yaml
  - gateway.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: victoriametrics-worker-values
    namespace: flux-system
    files:
      - values=values.yaml
