apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: service
spec:
  schema:
    apiVersion: v1alpha1
    kind: Service
    types:
      Port:
        port: integer | required=true
        protocol: string | required=true
    spec:
      name: string | required=true
      replicas: integer | default=2
      image: string | required=true
      imagePullPolicy: string | default=Always
      hostname: string | required=false
      ports: "[]Port"
      resources:
        limits:
          cpu: string | required=true
          memory: string | required=true
        requests:
          cpu: string | required=true
          memory: string | required=true

  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $${schema.spec.name}
        spec:
          replicas: $${schema.spec.replicas}
          selector:
            matchLabels:
              app: deployment
          template:
            metadata:
              labels:
                app: deployment
            spec:
              topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: topology.kubernetes.io/zone
                  whenUnsatisfiable: ScheduleAnyway
                  labelSelector:
                    matchLabels:
                      app: deployment
              containers:
                - name: $${schema.spec.name}-deployment
                  image: $${schema.spec.image}
                  imagePullPolicy: $${schema.spec.imagePullPolicy}
                  ports: '$${schema.spec.ports.map(p, {"containerPort": p.port, "protocol": p.protocol})}'
                  resources:
                    limits:
                      cpu: $${schema.spec.resources.limits.cpu}
                      memory: $${schema.spec.resources.limits.memory}
                    requests:
                      cpu: $${schema.spec.resources.requests.cpu}
                      memory: $${schema.spec.resources.requests.memory}
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: $${schema.spec.name}
          labels:
            networking.istio.io/traffic-distribution: PreferSameZone # Prefer same AZ/same node endpoints (istio)
        spec:
          trafficDistribution: PreferClose # Prefer same AZ/same node endpoints (k8s)
          selector:
            app: deployment
          ports: $${schema.spec.ports}

    - id: httpRoute
      includeWhen:
        - $${schema.spec.hostname.size() > 0}
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: $${schema.spec.name}
        spec:
          parentRefs:
            - name: traefik-gateway # north-south
              namespace: traefik
            - name: waypoint # east-west
              kind: Gateway
              namespace: $${schema.spec.namespace}
          hostnames:
            - $${schema.spec.hostname}.${DOMAIN}
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /
              backendRefs:
                - name: $${schema.spec.name}
                  port: $${schema.spec.ports[0].port}

    - id: serviceAccount
      template:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: $${schema.spec.name}
          namespace: $${schema.spec.namespace}
        automountServiceAccountToken: false
