apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: meshed-namespace
spec:
  schema:
    apiVersion: v1alpha1
    group: bellroy.com
    kind: MeshedNamespace
    scope: Cluster
    spec:
      name: string | required=true

  resources:
    - id: ns
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.name}
          annotations:
            linkerd.io/inject: enabled
          labels:
            pod-security.kubernetes.io/enforce: baseline
            pod-security.kubernetes.io/warn: restricted
            pod-security.kubernetes.io/audit: restricted

    - id: allowSameNamespaceCommunication
      template:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-same-namespace-communication
          namespace: ${ns.metadata.name}
        spec:
          podSelector: {}
          policyTypes:
            - Ingress
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: ${schema.spec.name}

    - id: egressPolicyAllowExternalTraffic
      template:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-external-egress
          namespace: ${ns.metadata.name}
        spec:
          podSelector: {}
          policyTypes:
            - Egress
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
                    except:
                      - 10.0.0.0/8
                      - 172.16.0.0/12
                      - 192.168.0.0/16

    - id: egressPolicyAllowDNSResolution
      template:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-dns-resolution
          namespace: ${ns.metadata.name}
        spec:
          podSelector: {}
          policyTypes:
            - Egress
          egress:
            # kubeDNS resolution
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - protocol: UDP
                  port: 53
                - protocol: TCP
                  port: 53

    - id: egressPolicyAllowLinkerdCertRetrieval
      template:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-linkerd-cert-retrieval
          namespace: ${ns.metadata.name}
        spec:
          podSelector: {}
          policyTypes:
            - Egress
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      linkerd.io/control-plane-ns: linkerd
              ports:
                - protocol: TCP
                  port: 8086   # destination service
                - protocol: TCP
                  port: 8080   # identity service
                - protocol: TCP
                  port: 8090   # policy controller
