apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: service
spec:
  schema:
    apiVersion: v1alpha1
    kind: Service
    types:
      Port:
        port: integer | required=true
        protocol: string | required=true
    spec:
      name: string | required=true
      replicas: integer | default=2
      image: string | required=true
      imagePullPolicy: string | default=Always
      hostname: string | required=false
      ports: "[]Port"
      resources:
        limits:
          cpu: string | required=true
          memory: string | required=true
        requests:
          cpu: string | required=true
          memory: string | required=true

  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $${schema.spec.name}
          namespace: $${schema.metadata.namespace}
        spec:
          replicas: $${schema.spec.replicas}
          selector:
            matchLabels:
              app: deployment
          template:
            metadata:
              labels:
                app: deployment
            spec:
              topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: topology.kubernetes.io/zone
                  whenUnsatisfiable: ScheduleAnyway
                  labelSelector:
                    matchLabels:
                      app: deployment
              containers:
                - name: $${schema.spec.name}-deployment
                  image: $${schema.spec.image}
                  imagePullPolicy: $${schema.spec.imagePullPolicy}
                  ports: '$${schema.spec.ports.map(p, {"containerPort": p.port, "protocol": p.protocol})}'
                  resources:
                    limits:
                      cpu: $${schema.spec.resources.limits.cpu}
                      memory: $${schema.spec.resources.limits.memory}
                    requests:
                      cpu: $${schema.spec.resources.requests.cpu}
                      memory: $${schema.spec.resources.requests.memory}

    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: $${schema.spec.name}
          namespace: $${schema.metadata.namespace}
        spec:
          trafficDistribution: PreferClose # Prefer same AZ/same node endpoints (k8s)
          selector:
            app: deployment
          ports: $${schema.spec.ports}

    # north-south
    - id: httpRoute
      includeWhen:
        - $${schema.spec.hostname.size() > 0}
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: $${schema.spec.name}
          namespace: $${schema.metadata.namespace}
        spec:
          parentRefs:
            - name: traefik-gateway # north-south
              namespace: traefik
          hostnames:
            - $${schema.spec.hostname}.${domain}
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /
              backendRefs:
                - name: $${schema.spec.name}
                  port: $${schema.spec.ports[0].port}


    - id: serviceAccount # TODO: figure out proper RBAC...
      template:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: $${schema.spec.name}
          namespace: $${schema.metadata.namespace}
        automountServiceAccountToken: false


    ## Linkerd mTLS polcies

    # Who is allowed to call my-app
    - id: linkerdServer
      apiVersion: policy.linkerd.io/v1beta3
      kind: Server
      metadata:
        name: $${schema.spec.name}
        namespace: $${schema.metadata.namespace}
      spec:
        podSelector:
          matchLabels:
            app: $${schema.spec.name}
        port: $${schema.spec.ports[0].port}
        proxyProtocol: HTTP/2

    - id: linkerdHttpRoute
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: $${schema.spec.name}-mesh-route
          namespace: $${schema.metadata.namespace}
        spec:
          parentRefs:
            - name: $${schema.spec.name}
              kind: Service
              group: policy.linkerd.io
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    # must include healthchecks
                    value: /


    - id: traefikMeshAuthentication
      apiVersion: policy.linkerd.io/v1beta3
      kind: MeshTLSAuthentication
      metadata:
        name: traefik-mesh-identity
        namespace: $${schema.metadata.namespace}
      spec:
        identityRefs:
          - kind: ServiceAccount
            name: traefik-traefik
            namespace: traefik

    - id: allowTraefikAndKubeletToService
      apiVersion: policy.linkerd.io/v1beta3
      kind: AuthorizationPolicy
      metadata:
        name: $${schema.spec.name}-allow-traefik
        namespace: $${schema.metadata.namespace}
      spec:
        targetRef:
          group: policy.linkerd.io
          kind: HTTPRoute
          name: $${schema.spec.name}-mesh-route
        requiredAuthenticationRefs:
          - name: traefik-mesh-identity
            kind: MeshTLSAuthentication
            group: policy.linkerd.io
          - name: kubelet-network-auth
            kind: NetworkAuthentication
            group: policy.linkerd.io
