apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: service
spec:
  schema:
    apiVersion: v1alpha1
    kind: MeshedService
    scope: Namespaced
    types:
      Port:
        port: integer | required=true
        protocol: string | required=true

      HttpHeaders:
        name: string
        value: string

      Probe:
        httpGet:
          path: string | required=true
          port: integer | required=true
          httpHeaders: '[]HttpHeaders'

        initialDelaySeconds: integer | default=15
        periodSeconds: integer | default=5
        timeoutSeconds: integer | default=3
        failureThreshold: integer | default=3

    spec:
      name: string | required=true
      replicas: integer | default=2
      container:
        image: string | required=true
        imagePullPolicy: string | default=Always
        ports: "[]Port"

      ingress:
        hostname: string | required=false
        path: string | default=/
        enabled:
          externally: boolean | default=false
          internal: boolean | default=false


      livenessProbe: Probe | required=false
      startupProbe: Probe | required=false
      readinessProbe: Probe | required=false

      resources:
        limits:
          cpu: string | required=true
          memory: string | required=true
        requests:
          cpu: string | required=true
          memory: string | required=true

  resources:
    - id: clusterVars
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: cluster-vars
          namespace: flux-operator

    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
        spec:
          replicas: ${schema.spec.replicas}
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: topology.kubernetes.io/zone
                  whenUnsatisfiable: ScheduleAnyway
                  labelSelector:
                    matchLabels:
                      app: ${schema.spec.name}
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.container.image}
                  imagePullPolicy: ${schema.spec.container.imagePullPolicy}
                  ports: '${schema.spec.container.ports.map(p, {"containerPort": p.port, "protocol": p.protocol})}'
                  resources:
                    limits:
                      cpu: ${schema.spec.resources.limits.cpu}
                      memory: ${schema.spec.resources.limits.memory}
                    requests:
                      cpu: ${schema.spec.resources.requests.cpu}
                      memory: ${schema.spec.resources.requests.memory}
                  securityContext:
                    runAsNonRoot: true
                    allowPrivilegeEscalation: false
                    seccompProfile:
                      type: RuntimeDefault
                    capabilities:
                      drop: ["ALL"]

    - id: svc
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}
        spec:
          trafficDistribution: PreferClose # Prefer same AZ/same node endpoints (k8s)
          selector:
            app: ${schema.spec.name}
          ports: '${schema.spec.container.ports.map(p, {"port": p.port, "targetPort": p.port, "protocol": p.protocol})}'

    - id: serviceAccount # TODO: figure out proper RBAC...
      template:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: ${schema.spec.name}
        automountServiceAccountToken: false

    - id: northSouthHTTPRoute
      includeWhen:
        - ${schema.spec.ingress.enabled.externally}
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.spec.name}
        spec:
          parentRefs:
            - name: traefik-gateway # north-south
              namespace: traefik
              sectionName: websecure
          hostnames:
            - ${schema.spec.ingress.hostname + "." + clusterVars.data.?domain.orValue("")}
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: ${schema.spec.ingress.path}
              backendRefs:
                - name: ${schema.spec.name}
                  port: ${schema.spec.container.ports[0].port}

    ## Linkerd mTLS policies
    - id: linkerdServer
      includeWhen:
        - ${schema.spec.ingress.enabled.externally || schema.spec.ingress.enabled.internal}
      template:
        apiVersion: policy.linkerd.io/v1beta1
        kind: Server
        metadata:
          name: ${schema.spec.name}
        spec:
          podSelector:
            matchLabels:
              app: ${schema.spec.name}
          port: ${schema.spec.container.ports[0].port}
          proxyProtocol: HTTP/2

    - id: eastWestHTTPRoute
      includeWhen:
        - ${schema.spec.ingress.enabled.internal}
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.spec.name}-mesh-route
        spec:
          parentRefs:
            - name: ${schema.spec.name}
              kind: Server
              group: policy.linkerd.io
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    # must include healthchecks
                    value: ${schema.spec.ingress.path}

    - id: authenticateAllMeshedClients
      includeWhen:
        - ${schema.spec.ingress.enabled.externally || schema.spec.ingress.enabled.internal}
      template:
        apiVersion: policy.linkerd.io/v1alpha1
        kind: MeshTLSAuthentication
        metadata:
          name: ${schema.spec.name}-all-meshed-clients
        spec:
          identities:
            - "*"

    - id: authorizeAllMeshedClientsToAccessMyHTTPRoute
      includeWhen:
        - ${schema.spec.ingress.enabled.externally || schema.spec.ingress.enabled.internal}
      template:
        apiVersion: policy.linkerd.io/v1alpha1
        kind: AuthorizationPolicy
        metadata:
          name: ${schema.spec.name}-allow-mesh
        spec:
          targetRef:
            group: policy.linkerd.io
            kind: HTTPRoute
            name: ${schema.spec.name}-mesh-route
          requiredAuthenticationRefs:
            - name: ${authenticateAllMeshedClients.metadata.name}
              kind: MeshTLSAuthentication
              group: policy.linkerd.io
